[workspace]
authors = ["lkless <leakless21@gmail.com>"]
channels = ["conda-forge"]
name = "ViStreamASR"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<3.12"
pytest = ">=8.4.1,<9"

[pypi-dependencies]
librosa = ">=0.11.0, <0.12"
numba = ">=0.61.2, <0.62"
llvmlite = ">=0.44.0, <0.45"
numpy = ">=2.2.6, <3"
requests = ">=2.32.4, <3"
torch = ">=2.7.1, <3"
torchaudio = ">=2.7.1, <3"
silero-vad = ">=5.1.2, <6"
flashlight-text = ">=0.0.7, <0.0.8"

vistreamasr = { path = ".", editable = true }
sounddevice = ">=0.5.2, <0.6"
